eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://minion.eureka.machine:8761/eureka/
ribbon:
  ServerListRefreshInterval: 5000

logging:
  level:
    com.netflix.discovery: 'OFF'

